//! Vault create / scaffold helpers.

use crate::core::error::AppError;
use crate::features::catalog;
use serde::Serialize;
use std::fs;
use std::path::Path;

/// Default AGENTS.md template written on Create Vault (only if missing).
pub const AGENTS_MD_TEMPLATE: &str = r#"# AGENTS.md

This file is the L0 map for agents working in this Agentero research vault.

## Layout

- `papers/` — paper folders (any depth). A **paper folder** is the minimal unit: it contains `NOTES.md`, optional `PAPER.md` / `marks/`, and `source/`.
- `notes/` — free-form concept notes and ideas (`[[wikilinks]]` welcome).
- `plans/` — research plans and drafts.
- `.agents/` — vault-local agent assets (e.g. `skills/<id>/SKILL.md` for Composer `$` skills).
- `.agentero/catalog.sqlite` — paper **catalog** (collection + metadata). There is usually **no** root `PAPERS.md` or `library.bib` unless the user exports them.
- Headless tooling: optional **`agentero` CLI** (discover / list / import). Prefer skill **`agentero-cli`** (`$agentero-cli` / `/agentero-cli`) with `--json`. CLI does **not** run agents or paper-reader.

## Paper reading order

For a paper folder, use the richest available source in this order:

1. `source/**/*.{tex,ltx}` — original LaTeX source; prefer this for structure, equations, citations, and experiments.
2. `{paper}/PAPER.md` — derived readable text generated by LiteParse from the PDF when no TeX is available.
3. If there is no TeX and no `PAPER.md`, run `agentero paper parse {paper}` to generate `PAPER.md` with LiteParse, then read the generated file.
4. A local PDF under the paper folder — last-resort source when parsing is unavailable or the generated body is incomplete.

`NOTES.md` is the user's working note, not the paper's source text. Read it for existing context, preserve user-written content, and never treat it as a replacement for the paper body.

## Rules

- Prefer short, structured notes (problem / method / results).
- Keep original files under `source/` unchanged; treat `PAPER.md` as a derived, regenerable artifact.
- Do not invent facts, numbers, citations, or experimental conclusions. Mark uncertainty explicitly.
- Keep `[[wikilinks]]` as written; do not rewrite them to plain URLs.
- Cite the Vault-relative paths actually read; end substantial answers with `## Sources`.
- Never overwrite user notes without an explicit draft + confirmation path.
- Do not store API keys or other secrets in the Vault.
"#;

/// Scaffold for `.agents/README.md` (only if missing).
pub const AGENTS_DIR_README: &str = include_str!("../../../../templates/vault/.agents/README.md");

/// Skills index: bundled presets, third-party source + LICENSE.
pub const SKILLS_DIR_README: &str =
    include_str!("../../../../templates/vault/.agents/skills/README.md");

/// Supervisor-Skills (HKUSTDial) CC BY-NC-SA 4.0 text.
pub const SUPERVISOR_SKILLS_LICENSE: &str =
    include_str!("../../../../templates/vault/.agents/skills/LICENSE-Supervisor-Skills.txt");

/// Bundled paper-reader skill (file-tree Zap workflow).
pub const PAPER_READER_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/paper-reader/SKILL.md");

/// Bundled agentero-cli skill (headless vault discover/import via CLI).
pub const AGENTERO_CLI_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/agentero-cli/SKILL.md");

/// Bundled vault-normalizer skill (directory migration into Agentero layout).
pub const VAULT_NORMALIZER_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/vault-normalizer/SKILL.md");

/// Bundled idea-evaluator skill (from Supervisor-Skills).
pub const IDEA_EVALUATOR_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/idea-evaluator/SKILL.md");

/// Bundled deep-research skill (from Supervisor-Skills).
pub const DEEP_RESEARCH_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/deep-research/SKILL.md");

/// Vault-relative path → content for bundled skill seeding (no overwrite).
/// Paths are under the vault root (e.g. `.agents/skills/...`).
///
/// When the app ships new skills, [`ensure_vault`] / [`create_vault`] add any
/// missing paths here; existing files are left untouched so user edits survive.
pub(crate) fn bundled_skill_files() -> &'static [(&'static str, &'static str)] {
    &[
        (".agents/skills/README.md", SKILLS_DIR_README),
        (
            ".agents/skills/LICENSE-Supervisor-Skills.txt",
            SUPERVISOR_SKILLS_LICENSE,
        ),
        (".agents/skills/paper-reader/SKILL.md", PAPER_READER_SKILL),
        (".agents/skills/agentero-cli/SKILL.md", AGENTERO_CLI_SKILL),
        (
            ".agents/skills/vault-normalizer/SKILL.md",
            VAULT_NORMALIZER_SKILL,
        ),
        // idea-evaluator (Supervisor-Skills)
        (
            ".agents/skills/idea-evaluator/SKILL.md",
            IDEA_EVALUATOR_SKILL,
        ),
        (
            ".agents/skills/idea-evaluator/references/domain-evaluation-frameworks.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/domain-evaluation-frameworks.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/fatal-flaws.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/fatal-flaws.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/five-dimensions.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/five-dimensions.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/lifecycle-capability-matching.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/lifecycle-capability-matching.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-elephant.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-elephant.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-examples.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-examples.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-first-principles.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-first-principles.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-hamming.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-hamming.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-shift-probe.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-shift-probe.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-technology-cycle.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-technology-cycle.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/worked-examples.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/worked-examples.md"
            ),
        ),
        // deep-research (Supervisor-Skills)
        (
            ".agents/skills/deep-research/SKILL.md",
            DEEP_RESEARCH_SKILL,
        ),
        (
            ".agents/skills/deep-research/references/citation-protocol.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/citation-protocol.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/hedge-calibration.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/hedge-calibration.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/output-structure.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/output-structure.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/quality-gates.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/quality-gates.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/search-strategy.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/search-strategy.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/self-adversarial.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/self-adversarial.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/synthesis-framework.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/synthesis-framework.md"
            ),
        ),
    ]
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateVaultResult {
    pub path: String,
    pub created: Vec<String>,
    /// Relative path suggested for first open (e.g. `AGENTS.md`).
    pub open_path: String,
}

fn join_rel(root: &Path, rel: &str) -> std::path::PathBuf {
    let mut p = root.to_path_buf();
    for part in rel.split('/').filter(|s| !s.is_empty()) {
        p.push(part);
    }
    p
}

/// Write `rel` under `root` if missing. Creates parent dirs. Records `rel` in `created`.
fn seed_file_if_missing(
    root: &Path,
    rel: &str,
    content: &str,
    created: &mut Vec<String>,
) -> Result<(), AppError> {
    let path = join_rel(root, rel);
    if path.exists() {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, content)?;
    created.push(rel.into());
    Ok(())
}

/// Idempotent vault scaffold under `path` without overwriting existing user files.
///
/// Creates: `papers/`, `notes/`, `plans/`, `.agentero/`, `.agents/` (+ `skills/`),
/// `AGENTS.md` (if missing), seeds `.agents/README.md` and **any missing** bundled
/// skills from the app template, and initializes `.agentero/catalog.sqlite`.
/// Does **not** create `PAPERS.md` / `library.bib`.
///
/// Safe to call on every vault open after an app update so newly shipped skills
/// appear under `.agents/skills/` while customized files stay intact.
pub fn ensure_vault(path: &Path) -> Result<CreateVaultResult, AppError> {
    if !path.exists() {
        fs::create_dir_all(path)?;
    }
    if !path.is_dir() {
        return Err(AppError::message(format!(
            "not a directory: {}",
            path.display()
        )));
    }

    let mut created: Vec<String> = Vec::new();

    for dir in [
        "papers",
        "notes",
        "plans",
        ".agentero",
        ".agents",
        ".agents/skills",
    ] {
        let p = join_rel(path, dir);
        if !p.exists() {
            fs::create_dir_all(&p)?;
            created.push(format!("{dir}/"));
        }
    }

    let agents_md = join_rel(path, "AGENTS.md");
    if !agents_md.exists() {
        fs::write(&agents_md, AGENTS_MD_TEMPLATE)?;
        created.push("AGENTS.md".into());
    }

    // Seed vault-local agent layout from `templates/vault/.agents/` (no overwrite).
    // Includes newly bundled skills that did not exist when the vault was first created.
    seed_file_if_missing(path, ".agents/README.md", AGENTS_DIR_README, &mut created)?;
    for (rel, content) in bundled_skill_files() {
        seed_file_if_missing(path, rel, content, &mut created)?;
    }

    // Catalog: always ensure schema (may create catalog.sqlite)
    let db_path = catalog::catalog_db_path(path);
    let db_existed = db_path.exists();
    let conn = catalog::ensure_catalog(path)?;
    drop(conn);
    if !db_existed && db_path.exists() {
        created.push(".agentero/catalog.sqlite".into());
    }

    let path_str = path
        .canonicalize()
        .unwrap_or_else(|_| path.to_path_buf())
        .to_string_lossy()
        .to_string();

    Ok(CreateVaultResult {
        path: path_str,
        created,
        open_path: "AGENTS.md".into(),
    })
}

/// Create Agentero vault skeleton (alias of [`ensure_vault`]).
pub fn create_vault(path: &Path) -> Result<CreateVaultResult, AppError> {
    ensure_vault(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    #[test]
    fn create_vault_scaffolds_dirs_and_catalog() {
        let dir = env::temp_dir().join(format!("agentero-vault-create-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let r = create_vault(&dir).expect("create");
        assert!(dir.join("papers").is_dir());
        assert!(dir.join("notes").is_dir());
        assert!(dir.join("plans").is_dir());
        assert!(dir.join(".agentero").is_dir());
        assert!(dir.join(".agents").is_dir());
        assert!(dir.join(".agents/skills").is_dir());
        assert!(dir.join(".agents/README.md").is_file());
        assert!(dir.join(".agents/skills/README.md").is_file());
        assert!(dir
            .join(".agents/skills/LICENSE-Supervisor-Skills.txt")
            .is_file());
        assert!(dir.join(".agents/skills/paper-reader/SKILL.md").is_file());
        assert!(dir.join(".agents/skills/agentero-cli/SKILL.md").is_file());
        assert!(dir.join(".agents/skills/idea-evaluator/SKILL.md").is_file());
        assert!(dir
            .join(".agents/skills/idea-evaluator/references/five-dimensions.md")
            .is_file());
        assert!(dir.join(".agents/skills/deep-research/SKILL.md").is_file());
        assert!(dir
            .join(".agents/skills/deep-research/references/quality-gates.md")
            .is_file());
        assert!(dir.join("AGENTS.md").is_file());
        assert!(dir.join(".agentero/catalog.sqlite").is_file());
        assert!(!dir.join("PAPERS.md").exists());
        assert!(!dir.join("library.bib").exists());
        assert!(r
            .created
            .iter()
            .any(|c| c.contains("catalog") || c == "AGENTS.md" || c.ends_with('/')));
        assert!(r.created.iter().any(|c| c.starts_with(".agents")));

        // Second call does not wipe AGENTS.md or .agents/README.md
        fs::write(dir.join("AGENTS.md"), "# custom\n").unwrap();
        fs::write(dir.join(".agents/README.md"), "# keep\n").unwrap();
        let r2 = create_vault(&dir).expect("again");
        let content = fs::read_to_string(dir.join("AGENTS.md")).unwrap();
        assert!(content.starts_with("# custom"));
        assert!(!r2.created.iter().any(|c| c == "AGENTS.md"));
        let agents_readme = fs::read_to_string(dir.join(".agents/README.md")).unwrap();
        assert!(agents_readme.starts_with("# keep"));
        assert!(!r2.created.iter().any(|c| c == ".agents/README.md"));

        let _ = fs::remove_dir_all(&dir);
    }

    /// After app update: missing bundled skills are added; customized files stay.
    #[test]
    fn ensure_vault_seeds_missing_bundled_skills_only() {
        let dir = env::temp_dir().join(format!(
            "agentero-vault-ensure-skills-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        create_vault(&dir).expect("create");

        // Simulate an older vault that lacked a later-bundled skill, plus a user edit.
        let deep = dir.join(".agents/skills/deep-research");
        let _ = fs::remove_dir_all(&deep);
        let paper_skill = dir.join(".agents/skills/paper-reader/SKILL.md");
        fs::write(&paper_skill, "# my custom paper-reader\n").unwrap();

        let r = ensure_vault(&dir).expect("ensure after update");
        assert!(
            r.created
                .iter()
                .any(|c| c.starts_with(".agents/skills/deep-research/")),
            "expected deep-research paths in created: {:?}",
            r.created
        );
        assert!(dir.join(".agents/skills/deep-research/SKILL.md").is_file());
        assert!(dir
            .join(".agents/skills/deep-research/references/quality-gates.md")
            .is_file());
        // User-edited skill must not be overwritten
        let paper = fs::read_to_string(&paper_skill).unwrap();
        assert!(paper.starts_with("# my custom paper-reader"));
        assert!(!r
            .created
            .iter()
            .any(|c| c == ".agents/skills/paper-reader/SKILL.md"));

        // Idempotent: second ensure adds nothing for already-present skills
        let r2 = ensure_vault(&dir).expect("ensure again");
        assert!(!r2
            .created
            .iter()
            .any(|c| c.starts_with(".agents/skills/deep-research/")));

        let _ = fs::remove_dir_all(&dir);
    }

    /// Optional smoke write:
    /// `AGENTERO_TEST_VAULT_PATH=$HOME/Downloads/agentero-from-rust cargo test create_vault_at_env_path -- --ignored --nocapture`
    #[test]
    #[ignore = "set AGENTERO_TEST_VAULT_PATH to write a real vault (e.g. under Downloads)"]
    fn create_vault_at_env_path() {
        let raw = env::var("AGENTERO_TEST_VAULT_PATH").expect("set AGENTERO_TEST_VAULT_PATH");
        let dir = Path::new(&raw);
        if dir.exists() {
            let _ = fs::remove_dir_all(dir);
        }
        fs::create_dir_all(dir).unwrap();
        let r = create_vault(dir).expect("create");
        assert!(dir.join(".agentero/catalog.sqlite").is_file());
        assert!(dir.join("AGENTS.md").is_file());
        assert!(dir.join("papers").is_dir());
        assert!(!dir.join("PAPERS.md").exists());
        eprintln!(
            "create_vault wrote {} items to {}",
            r.created.len(),
            dir.display()
        );
    }
}

/// Tauri command shells for this feature.
pub mod commands;
