//! Vault create / scaffold helpers.

use crate::core::error::AppError;
use crate::features::catalog;
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::Path;

/// Default AGENTS.md template written on Create Vault (only if missing).
pub const AGENTS_MD_TEMPLATE: &str = r#"# AGENTS.md

This file is the L0 map for agents working in this Agentero research vault.

## Layout

- `papers/` — paper folders (any depth). A **paper folder** is the minimal unit: it contains `NOTES.md`, optional `PAPER.md` / `marks/`, and `source/`.
- `notes/` — free-form concept notes and ideas. Supports `[[wikilinks]]`, `![[embeds]]`, Mermaid diagrams, and Obsidian `> [!callout]` blocks.
- `plans/` — research plans and drafts.
- `.agents/` — vault-local agent assets (e.g. `skills/<id>/SKILL.md` for Composer `$` skills).
- `.agentero/catalog.sqlite` — paper **catalog** (collection + metadata). There is usually **no** root `PAPERS.md` or `library.bib` unless the user exports them.
- Headless tooling: optional **`agentero` CLI** (discover / list / import). Prefer skill **`agentero-cli`** (`$agentero-cli` / `/agentero-cli`) with `--json`. CLI does **not** run agents or paper-reader.

## Paper reading order

For a paper folder, use the richest available source in this order:

1. `source/**/*.{tex,ltx}` — original LaTeX source; prefer this for structure, equations, citations, and experiments.
2. `{paper}/PAPER.md` — derived readable text generated by LiteParse from the PDF when no TeX is available.
3. If there is no TeX and no `PAPER.md`, run `agentero paper parse {paper}` to generate `PAPER.md` with LiteParse, then read the generated file.
4. A local PDF under the paper folder — last-resort source when parsing is unavailable or the generated body is incomplete.

`NOTES.md` is the user's working note, not the paper's source text. Read it for existing context, preserve user-written content, and never treat it as a replacement for the paper body.

## Rules

- Prefer short, structured notes (problem / method / results).
- Keep original files under `source/` unchanged; treat `PAPER.md` as a derived, regenerable artifact.
- Do not invent facts, numbers, citations, or experimental conclusions. Mark uncertainty explicitly.
- Keep `[[wikilinks]]` and `![[embeds]]` as written; do not rewrite them to plain URLs or inline text.
- Preserve Mermaid fenced code blocks (` ```mermaid `); do not flatten diagrams to prose.
- **Math in Markdown (Agentero / KaTeX):** write real math delimiters so NOTES render.
  - Inline: `$\eta > 1$` (not bare `(\eta > 1)` or undelimited `\eta > 1`).
  - Display / multi-line: `$$...$$` on their own lines.
  - Prefer `$` / `$$` over raw TeX parentheses `\(...\)` / `\[...\]` or pseudo-math in plain prose.
  - Escape a literal dollar as `\$` when it is not math.
- Cite the Vault-relative paths actually read; end substantial answers with `## Sources`.
- Never overwrite user notes without an explicit draft + confirmation path.
- Do not store API keys or other secrets in the Vault.
"#;

/// Scaffold for `.agents/README.md` (only if missing).
pub const AGENTS_DIR_README: &str = include_str!("../../../../templates/vault/.agents/README.md");

/// Skills index: bundled presets, third-party source + LICENSE.
pub const SKILLS_DIR_README: &str =
    include_str!("../../../../templates/vault/.agents/skills/README.md");

/// Supervisor-Skills (HKUSTDial) CC BY-NC-SA 4.0 text.
pub const SUPERVISOR_SKILLS_LICENSE: &str =
    include_str!("../../../../templates/vault/.agents/skills/LICENSE-Supervisor-Skills.txt");

/// Bundled paper-reader skill (file-tree Zap workflow).
pub const PAPER_READER_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/paper-reader/SKILL.md");

/// Bundled equation-annotation skill (symbol glossary → Annotation.md).
pub const EQUATION_ANNOTATION_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/equation-annotation/SKILL.md");

/// Bundled agentero-cli skill (headless vault discover/import via CLI).
pub const AGENTERO_CLI_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/agentero-cli/SKILL.md");

/// Bundled vault-normalizer skill (directory migration into Agentero layout).
pub const VAULT_NORMALIZER_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/vault-normalizer/SKILL.md");

/// Bundled idea-evaluator skill (from Supervisor-Skills).
pub const IDEA_EVALUATOR_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/idea-evaluator/SKILL.md");

/// Bundled deep-research skill (from Supervisor-Skills).
pub const DEEP_RESEARCH_SKILL: &str =
    include_str!("../../../../templates/vault/.agents/skills/deep-research/SKILL.md");

// Onboarding tutorial notes are discovered by build.rs and embedded here.
include!(concat!(env!("OUT_DIR"), "/onboarding_templates.rs"));

/// Vault-relative path → content for bundled skill seeding (no overwrite).
/// Paths are under the vault root (e.g. `.agents/skills/...`).
///
/// When the app ships new skills, [`ensure_vault`] / [`create_vault`] add any
/// missing paths here; existing files are left untouched so user edits survive.
pub(crate) fn bundled_skill_files() -> &'static [(&'static str, &'static str)] {
    &[
        (".agents/skills/README.md", SKILLS_DIR_README),
        (
            ".agents/skills/LICENSE-Supervisor-Skills.txt",
            SUPERVISOR_SKILLS_LICENSE,
        ),
        (".agents/skills/paper-reader/SKILL.md", PAPER_READER_SKILL),
        (
            ".agents/skills/equation-annotation/SKILL.md",
            EQUATION_ANNOTATION_SKILL,
        ),
        (".agents/skills/agentero-cli/SKILL.md", AGENTERO_CLI_SKILL),
        (
            ".agents/skills/vault-normalizer/SKILL.md",
            VAULT_NORMALIZER_SKILL,
        ),
        // idea-evaluator (Supervisor-Skills)
        (
            ".agents/skills/idea-evaluator/SKILL.md",
            IDEA_EVALUATOR_SKILL,
        ),
        (
            ".agents/skills/idea-evaluator/references/domain-evaluation-frameworks.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/domain-evaluation-frameworks.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/fatal-flaws.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/fatal-flaws.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/five-dimensions.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/five-dimensions.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/lifecycle-capability-matching.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/lifecycle-capability-matching.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-elephant.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-elephant.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-examples.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-examples.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-first-principles.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-first-principles.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-hamming.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-hamming.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-shift-probe.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-shift-probe.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/paradigm-technology-cycle.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/paradigm-technology-cycle.md"
            ),
        ),
        (
            ".agents/skills/idea-evaluator/references/worked-examples.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/idea-evaluator/references/worked-examples.md"
            ),
        ),
        // deep-research (Supervisor-Skills)
        (
            ".agents/skills/deep-research/SKILL.md",
            DEEP_RESEARCH_SKILL,
        ),
        (
            ".agents/skills/deep-research/references/citation-protocol.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/citation-protocol.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/hedge-calibration.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/hedge-calibration.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/output-structure.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/output-structure.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/quality-gates.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/quality-gates.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/search-strategy.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/search-strategy.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/self-adversarial.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/self-adversarial.md"
            ),
        ),
        (
            ".agents/skills/deep-research/references/synthesis-framework.md",
            include_str!(
                "../../../../templates/vault/.agents/skills/deep-research/references/synthesis-framework.md"
            ),
        ),
    ]
}

/// Previous first-party SKILL.md hashes eligible for an automatic bundled
/// update. Byte equality by SHA-256 proves that the user has not customized the
/// seeded file. Any other content is preserved.
const LEGACY_BUNDLED_SKILL_HASHES: &[(&str, &str)] = &[
    (
        ".agents/skills/agentero-cli/SKILL.md",
        "8195723fd1b75a7c8c396f382b2c5b079d812246a693c65be0b9cd91bfb70f67",
    ),
    // Initial paper-reader seed.
    (
        ".agents/skills/paper-reader/SKILL.md",
        "9ef2a2ccf6b251e11639a27877e86c1324dd3f05309b320679b60a1535e67bb2",
    ),
    // After wiki-check skill constraints (common vault pin; was missing from
    // legacy list so ensure_vault never upgraded these installs).
    (
        ".agents/skills/paper-reader/SKILL.md",
        "6a9b35c5bb6858039052e2a19bd3b75beddf0b60dbcd49e026fa94ba21c31e09",
    ),
    // Pre-aliases paper-reader (title-only NOTES shell era).
    (
        ".agents/skills/paper-reader/SKILL.md",
        "e8ded7c1b6eec291b8b7ad3069b45ce42708d422597eaa620a0e73103a9cc478",
    ),
    // paper-reader before required frontmatter aliases section.
    (
        ".agents/skills/paper-reader/SKILL.md",
        "af3173192e5e94c81d36599ecdc0ad2b95a7531afa099391d85672b992c41359",
    ),
    // paper-reader before required `created` date field.
    (
        ".agents/skills/paper-reader/SKILL.md",
        "15978a666783c48b3b4063c29191bba90c9053e4f0d65c35767509eecbc2691b",
    ),
    (
        ".agents/skills/vault-normalizer/SKILL.md",
        "bec14afc8ad2d9c8b3f2ad06c7c84ef6e99fe546a8c944b757213d743feb2f33",
    ),
];

fn sha256_hex(content: &[u8]) -> String {
    hex::encode(Sha256::digest(content))
}

fn matches_legacy_bundled_skill(rel: &str, content: &[u8], hashes: &[(&str, &str)]) -> bool {
    let hash = sha256_hex(content);
    hashes
        .iter()
        .any(|(path, legacy_hash)| *path == rel && *legacy_hash == hash)
}

pub(crate) fn is_legacy_bundled_skill(rel: &str, content: &[u8]) -> bool {
    matches_legacy_bundled_skill(rel, content, LEGACY_BUNDLED_SKILL_HASHES)
}

pub(crate) fn bundled_skill_has_legacy_version(rel: &str) -> bool {
    LEGACY_BUNDLED_SKILL_HASHES
        .iter()
        .any(|(path, _)| *path == rel)
}

/// Normalize a frontend/CLI locale preference to a supported onboarding locale.
/// Unknown or missing values fall back to English.
pub fn resolve_vault_locale(locale: &str) -> &str {
    match locale.trim().to_lowercase().as_str() {
        "zh-cn" | "zh" => "zh-CN",
        _ => "en",
    }
}

/// Vault-relative path → content for onboarding tutorial notes.
/// Files are written only if missing so user edits survive app updates.
pub(crate) fn bundled_onboarding_files(locale: &str) -> Vec<(&'static str, &'static str)> {
    let resolved = resolve_vault_locale(locale);
    BUNDLED_ONBOARDING_FILES
        .iter()
        .filter(|(entry_locale, _, _)| *entry_locale == resolved)
        .map(|(_, rel, content)| (*rel, *content))
        .collect()
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct CreateVaultResult {
    pub path: String,
    pub created: Vec<String>,
    /// Untouched first-party bundled skills upgraded to the current template.
    pub updated: Vec<String>,
    /// Relative path suggested for first open (e.g. `AGENTS.md`).
    pub open_path: String,
}

fn join_rel(root: &Path, rel: &str) -> std::path::PathBuf {
    let mut p = root.to_path_buf();
    for part in rel.split('/').filter(|s| !s.is_empty()) {
        p.push(part);
    }
    p
}

/// Write `rel` under `root` if missing. Creates parent dirs. Records `rel` in `created`.
fn seed_file_if_missing(
    root: &Path,
    rel: &str,
    content: &str,
    created: &mut Vec<String>,
) -> Result<(), AppError> {
    let path = join_rel(root, rel);
    if path.exists() {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&path, content)?;
    created.push(rel.into());
    Ok(())
}

/// Seed a missing bundled file, or update an untouched first-party SKILL.md
/// whose bytes match a known previous bundled version.
fn seed_or_upgrade_bundled_file_with_hashes(
    root: &Path,
    rel: &str,
    content: &str,
    created: &mut Vec<String>,
    updated: &mut Vec<String>,
    hashes: &[(&str, &str)],
) -> Result<(), AppError> {
    let path = join_rel(root, rel);
    if !path.exists() {
        return seed_file_if_missing(root, rel, content, created);
    }
    if !hashes.iter().any(|(path, _)| *path == rel) {
        return Ok(());
    }
    let existing = fs::read(&path)?;
    if existing != content.as_bytes() && matches_legacy_bundled_skill(rel, &existing, hashes) {
        fs::write(&path, content)?;
        updated.push(rel.to_string());
    }
    Ok(())
}

fn seed_or_upgrade_bundled_file(
    root: &Path,
    rel: &str,
    content: &str,
    created: &mut Vec<String>,
    updated: &mut Vec<String>,
) -> Result<(), AppError> {
    seed_or_upgrade_bundled_file_with_hashes(
        root,
        rel,
        content,
        created,
        updated,
        LEGACY_BUNDLED_SKILL_HASHES,
    )
}

/// Idempotent vault scaffold under `path` without overwriting existing user files.
///
/// Creates: `papers/`, `notes/`, `plans/`, `.agentero/`, `.agents/` (+ `skills/`),
/// `AGENTS.md` (if missing), seeds `.agents/README.md` and bundled skills from
/// the app template, safely upgrades untouched first-party skills, seeds
/// localized onboarding tutorial notes under `notes/`, and initializes
/// `.agentero/catalog.sqlite`.
/// Does **not** create `PAPERS.md` / `library.bib`.
///
/// Safe to call on every vault open after an app update so newly shipped skills
/// and onboarding notes appear while customized files stay intact.
pub fn ensure_vault(path: &Path, locale: &str) -> Result<CreateVaultResult, AppError> {
    if !path.exists() {
        fs::create_dir_all(path)?;
    }
    if !path.is_dir() {
        return Err(AppError::message(format!(
            "not a directory: {}",
            path.display()
        )));
    }

    let mut created: Vec<String> = Vec::new();
    let mut updated: Vec<String> = Vec::new();

    for dir in [
        "papers",
        "notes",
        "plans",
        ".agentero",
        ".agents",
        ".agents/skills",
    ] {
        let p = join_rel(path, dir);
        if !p.exists() {
            fs::create_dir_all(&p)?;
            created.push(format!("{dir}/"));
        }
    }

    let agents_md = join_rel(path, "AGENTS.md");
    if !agents_md.exists() {
        fs::write(&agents_md, AGENTS_MD_TEMPLATE)?;
        created.push("AGENTS.md".into());
    }

    // Seed vault-local agent layout from `templates/vault/.agents/`. Missing
    // files are created; known untouched first-party skills may be upgraded.
    seed_file_if_missing(path, ".agents/README.md", AGENTS_DIR_README, &mut created)?;
    for (rel, content) in bundled_skill_files() {
        seed_or_upgrade_bundled_file(path, rel, content, &mut created, &mut updated)?;
    }

    // Seed localized onboarding tutorial notes under `notes/` (no overwrite).
    let onboarding_files = bundled_onboarding_files(locale);
    for (rel, content) in &onboarding_files {
        seed_file_if_missing(path, rel, content, &mut created)?;
    }

    // Catalog: always ensure schema (may create catalog.sqlite)
    let db_path = catalog::catalog_db_path(path);
    let db_existed = db_path.exists();
    let conn = catalog::ensure_catalog(path)?;
    drop(conn);
    if !db_existed && db_path.exists() {
        created.push(".agentero/catalog.sqlite".into());
    }

    let path_str = path
        .canonicalize()
        .unwrap_or_else(|_| path.to_path_buf())
        .to_string_lossy()
        .to_string();

    // Open the first onboarding note when it is newly created; otherwise AGENTS.md.
    let open_path = onboarding_files
        .first()
        .and_then(|(rel, _)| {
            created
                .iter()
                .find(|c| c == rel)
                .map(|_| (*rel).to_string())
        })
        .unwrap_or_else(|| "AGENTS.md".into());

    Ok(CreateVaultResult {
        path: path_str,
        created,
        updated,
        open_path,
    })
}

/// Create Agentero vault skeleton (alias of [`ensure_vault`]).
pub fn create_vault(path: &Path, locale: &str) -> Result<CreateVaultResult, AppError> {
    ensure_vault(path, locale)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    #[test]
    fn create_vault_scaffolds_dirs_and_catalog() {
        let dir = env::temp_dir().join(format!("agentero-vault-create-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let r = create_vault(&dir, "en").expect("create");
        assert!(dir.join("papers").is_dir());
        assert!(dir.join("notes").is_dir());
        assert!(dir.join("plans").is_dir());
        assert!(dir.join(".agentero").is_dir());
        assert!(dir.join(".agents").is_dir());
        assert!(dir.join(".agents/skills").is_dir());
        assert!(dir.join(".agents/README.md").is_file());
        assert!(dir.join(".agents/skills/README.md").is_file());
        assert!(dir
            .join(".agents/skills/LICENSE-Supervisor-Skills.txt")
            .is_file());
        assert!(dir.join(".agents/skills/paper-reader/SKILL.md").is_file());
        assert!(dir.join(".agents/skills/agentero-cli/SKILL.md").is_file());
        assert!(dir.join(".agents/skills/idea-evaluator/SKILL.md").is_file());
        assert!(dir
            .join(".agents/skills/idea-evaluator/references/five-dimensions.md")
            .is_file());
        assert!(dir.join(".agents/skills/deep-research/SKILL.md").is_file());
        assert!(dir
            .join(".agents/skills/deep-research/references/quality-gates.md")
            .is_file());
        assert!(dir.join("AGENTS.md").is_file());
        assert!(dir.join(".agentero/catalog.sqlite").is_file());
        let onboarding_paths = bundled_onboarding_files("en")
            .into_iter()
            .map(|(rel, _)| rel.to_string())
            .collect::<Vec<_>>();
        assert_eq!(onboarding_paths.len(), 3);
        for rel in &onboarding_paths {
            assert!(dir.join(rel).is_file(), "missing onboarding note: {rel}");
        }
        assert_eq!(r.open_path, onboarding_paths[0]);
        assert!(!dir.join("PAPERS.md").exists());
        assert!(!dir.join("library.bib").exists());
        assert!(r
            .created
            .iter()
            .any(|c| c.contains("catalog") || c == "AGENTS.md" || c.ends_with('/')));
        assert!(r.created.iter().any(|c| c.starts_with(".agents")));
        assert!(r.created.iter().any(|c| c.starts_with("notes/")));

        // Second call does not wipe AGENTS.md, .agents/README.md, or onboarding notes
        fs::write(dir.join("AGENTS.md"), "# custom\n").unwrap();
        fs::write(dir.join(".agents/README.md"), "# keep\n").unwrap();
        fs::write(dir.join(&onboarding_paths[0]), "# edited\n").unwrap();
        let r2 = create_vault(&dir, "en").expect("again");
        let content = fs::read_to_string(dir.join("AGENTS.md")).unwrap();
        assert!(content.starts_with("# custom"));
        assert!(!r2.created.iter().any(|c| c == "AGENTS.md"));
        let agents_readme = fs::read_to_string(dir.join(".agents/README.md")).unwrap();
        assert!(agents_readme.starts_with("# keep"));
        assert!(!r2.created.iter().any(|c| c == ".agents/README.md"));
        let onboarding = fs::read_to_string(dir.join(&onboarding_paths[0])).unwrap();
        assert!(onboarding.starts_with("# edited"));
        assert!(!r2.created.iter().any(|c| c == &onboarding_paths[0]));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn localized_onboarding_files_are_flattened_under_notes() {
        for locale in ["en", "zh-CN"] {
            let onboarding_paths = bundled_onboarding_files(locale);
            assert_eq!(onboarding_paths.len(), 3, "locale: {locale}");
            for (rel, _) in onboarding_paths {
                assert_eq!(
                    Path::new(rel).parent(),
                    Some(Path::new("notes")),
                    "onboarding path must be directly under notes/: {rel}"
                );
                assert!(!rel.starts_with("notes/en/"));
                assert!(!rel.starts_with("notes/zh-CN/"));
            }
        }

        let dir = env::temp_dir().join(format!(
            "agentero-vault-create-zh-flat-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        let result = create_vault(&dir, "zh-CN").expect("create Chinese vault");
        assert!(dir.join("notes/01 论文导入与管理.md").is_file());
        assert!(!dir.join("notes/zh-CN").exists());
        assert_eq!(result.open_path, "notes/01 论文导入与管理.md");

        let _ = fs::remove_dir_all(&dir);
    }

    /// After app update: missing bundled skills are added and customized files stay.
    #[test]
    fn ensure_vault_seeds_missing_bundled_skills_without_overwriting_customized_files() {
        let dir = env::temp_dir().join(format!(
            "agentero-vault-ensure-skills-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        create_vault(&dir, "en").expect("create");

        // Simulate an older vault that lacked a later-bundled skill, plus a user edit.
        let deep = dir.join(".agents/skills/deep-research");
        let _ = fs::remove_dir_all(&deep);
        let paper_skill = dir.join(".agents/skills/paper-reader/SKILL.md");
        fs::write(&paper_skill, "# my custom paper-reader\n").unwrap();

        let r = ensure_vault(&dir, "en").expect("ensure after update");
        assert!(
            r.created
                .iter()
                .any(|c| c.starts_with(".agents/skills/deep-research/")),
            "expected deep-research paths in created: {:?}",
            r.created
        );
        assert!(dir.join(".agents/skills/deep-research/SKILL.md").is_file());
        assert!(dir
            .join(".agents/skills/deep-research/references/quality-gates.md")
            .is_file());
        // User-edited skill must not be overwritten
        let paper = fs::read_to_string(&paper_skill).unwrap();
        assert!(paper.starts_with("# my custom paper-reader"));
        assert!(!r
            .created
            .iter()
            .any(|c| c == ".agents/skills/paper-reader/SKILL.md"));
        assert!(!r
            .updated
            .iter()
            .any(|c| c == ".agents/skills/paper-reader/SKILL.md"));

        // Idempotent: second ensure adds nothing for already-present skills
        let r2 = ensure_vault(&dir, "en").expect("ensure again");
        assert!(!r2
            .created
            .iter()
            .any(|c| c.starts_with(".agents/skills/deep-research/")));
        assert!(r2.updated.is_empty());

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn bundled_skill_upgrade_requires_an_exact_known_hash() {
        let dir = env::temp_dir().join(format!(
            "agentero-vault-upgrade-skill-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let rel = ".agents/skills/example/SKILL.md";
        let path = join_rel(&dir, rel);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, "old bundled skill\n").unwrap();
        let legacy_hash = sha256_hex(b"old bundled skill\n");
        let hashes = [(rel, legacy_hash.as_str())];
        let mut created = Vec::new();
        let mut updated = Vec::new();

        seed_or_upgrade_bundled_file_with_hashes(
            &dir,
            rel,
            "new bundled skill\n",
            &mut created,
            &mut updated,
            &hashes,
        )
        .unwrap();
        assert!(created.is_empty());
        assert_eq!(updated, vec![rel]);
        assert_eq!(fs::read_to_string(&path).unwrap(), "new bundled skill\n");

        fs::write(&path, "user customization\n").unwrap();
        updated.clear();
        seed_or_upgrade_bundled_file_with_hashes(
            &dir,
            rel,
            "another bundled skill\n",
            &mut created,
            &mut updated,
            &hashes,
        )
        .unwrap();
        assert!(updated.is_empty());
        assert_eq!(fs::read_to_string(&path).unwrap(), "user customization\n");

        let _ = fs::remove_dir_all(&dir);
    }

    /// Optional smoke write:
    /// `AGENTERO_TEST_VAULT_PATH=$HOME/Downloads/agentero-from-rust cargo test create_vault_at_env_path -- --ignored --nocapture`
    #[test]
    #[ignore = "set AGENTERO_TEST_VAULT_PATH to write a real vault (e.g. under Downloads)"]
    fn create_vault_at_env_path() {
        let raw = env::var("AGENTERO_TEST_VAULT_PATH").expect("set AGENTERO_TEST_VAULT_PATH");
        let dir = Path::new(&raw);
        if dir.exists() {
            let _ = fs::remove_dir_all(dir);
        }
        fs::create_dir_all(dir).unwrap();
        let r = create_vault(dir, "en").expect("create");
        assert!(dir.join(".agentero/catalog.sqlite").is_file());
        assert!(dir.join("AGENTS.md").is_file());
        assert!(dir.join("papers").is_dir());
        assert!(!dir.join("PAPERS.md").exists());
        eprintln!(
            "create_vault wrote {} items to {}",
            r.created.len(),
            dir.display()
        );
    }
}

/// Tauri command shells for this feature.
pub mod commands;
pub mod tree;
