// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	translateText: (args: TranslateTextArgs) =>
		__TAURI_INVOKE<ApiResult<TranslateTextResult>>("translate_text", { args }),
};

/* Types */
export type ApiResult<T> = {
	ok: boolean;
	data: T | null;
	error: ErrorBody | null;
};

export type ErrorBody = {
	code: string;
	message: string;
};

export type TranslateTextArgs = {
	text: string;
	sourceLang?: string;
	targetLang: string;
	/**  Free engine id: google | googleapi | bing | youdao | deeplx | huoshanweb | tencenttransmart | libre */
	provider?: string;
	/**  LibreTranslate base URL when provider=libre. */
	freeBaseUrl?: string | null;
	/**
	 *  Optional request timeout in milliseconds (clamped 1s–30s). Default 30s.
	 *  Settings probe uses a shorter value for snappy parallel checks.
	 */
	timeoutMs?: number | null;
};

export type TranslateTextResult = {
	text: string;
	provider: string;
};
